http:
  port: 8003
  shutdownTimeout: 20

tg:
  # TODO:
  token: token
ton:
  # TODO:
  url: https://ton-blockchain.github.io/testnet-global.config.json

env:
  name: minton-gateway
  mode: prod       # 系统运行模式

log:                # 日志配置
  filename: ./log/minton-gateway.log
  maxSize: 256      # 日志文件的最大大小(兆)
  maxBackups: 20    # 保留旧文件的最大个数
  maxAge: 14         # 保留旧文件的最大天数
  level: -1         # 日志级别 @see zap log level

mysql:
  username: todo
  password: ""
  addr: "127.0.0.1:3306"
  database: "miniton"