package area

import (
	"encoding/json"
	"strconv"
)

var CountrysJson = `[
    {"country_eng":"Afghanistan","country_chn":"阿富汗","country_code":"70069"},
    {"country_eng":"Aland","country_chn":"奥兰","country_code":"180000"},
    {"country_eng":"Albania","country_chn":"阿尔巴尼亚","country_code":"49454"},
    {"country_eng":"Algeria","country_chn":"阿尔及利亚","country_code":"70053"},
    {"country_eng":"American Samoa","country_chn":"美属萨摩亚","country_code":"240000"},
    {"country_eng":"Andorra","country_chn":"安道尔","country_code":"70002"},
    {"country_eng":"Angola","country_chn":"安哥拉","country_code":"70082"},
    {"country_eng":"Anguilla","country_chn":"安圭拉","country_code":"54020"},
    {"country_eng":"Antigua and Barbuda","country_chn":"安提瓜和巴布达","country_code":"54001"},
    {"country_eng":"Argentina","country_chn":"阿根廷","country_code":"39874"},
    {"country_eng":"Armenia","country_chn":"亚美尼亚","country_code":"70021"},
    {"country_eng":"Aruba","country_chn":"阿鲁巴","country_code":"54016"},
    {"country_eng":"Australia","country_chn":"澳大利亚","country_code":"31000"},
    {"country_eng":"Austria","country_chn":"奥地利","country_code":"50147"},
    {"country_eng":"Azerbaijan","country_chn":"阿塞拜疆","country_code":"70024"},
    {"country_eng":"Bahamas","country_chn":"巴哈马","country_code":"390000"},
    {"country_eng":"Bahrain","country_chn":"巴林","country_code":"70067"},
    {"country_eng":"Bangladesh","country_chn":"孟加拉国","country_code":"70013"},
    {"country_eng":"Barbados","country_chn":"巴巴多斯","country_code":"54037"},
    {"country_eng":"Belarus","country_chn":"白俄罗斯","country_code":"70033"},
    {"country_eng":"Belgium","country_chn":"比利时","country_code":"50292"},
    {"country_eng":"Belize","country_chn":"伯利兹","country_code":"54027"},
    {"country_eng":"Benin","country_chn":"贝宁","country_code":"70077"},
    {"country_eng":"Bermuda","country_chn":"百慕大","country_code":"54024"},
    {"country_eng":"Bhutan","country_chn":"不丹","country_code":"70001"},
    {"country_eng":"Bolivia","country_chn":"玻利维亚","country_code":"40717"},
    {"country_eng":"Bonaire, Sint Eustatius and Saba","country_chn":"博内尔、圣尤斯特歇斯和沙巴","country_code":"340000"},
    {"country_eng":"Bosnia and Herzegovina","country_chn":"波黑","country_code":"70018"},
    {"country_eng":"Botswana","country_chn":"博茨瓦纳","country_code":"70036"},
    {"country_eng":"Bouvet Island","country_chn":"布韦岛","country_code":"500000"},
    {"country_eng":"Brazil","country_chn":"巴西","country_code":"39797"},
    {"country_eng":"British Indian Ocean Territory","country_chn":"英属印度洋领地","country_code":"1170000"},
    {"country_eng":"British Sovereign Base Areas","country_chn":"英属基地区","country_code":"52709"},
    {"country_eng":"British Virgin Islands","country_chn":"英属维尔京群岛","country_code":"54009"},
    {"country_eng":"Brunei","country_chn":"文莱","country_code":"31020"},
    {"country_eng":"Bulgaria","country_chn":"保加利亚","country_code":"48180"},
    {"country_eng":"Burkina Faso","country_chn":"布基纳法索","country_code":"70047"},
    {"country_eng":"Burundi","country_chn":"布隆迪","country_code":"70040"},
    {"country_eng":"Cabo Verde","country_chn":"佛得角","country_code":"70057"},
    {"country_eng":"Cambodia","country_chn":"柬埔寨","country_code":"70011"},
    {"country_eng":"Cameroon","country_chn":"喀麦隆","country_code":"70080"},
    {"country_eng":"Canada","country_chn":"加拿大","country_code":"54015"},
    {"country_eng":"Cayman Islands","country_chn":"开曼群岛","country_code":"54038"},
    {"country_eng":"Central African Republic","country_chn":"中非共和国","country_code":"70050"},
    {"country_eng":"Chad","country_chn":"乍得","country_code":"70048"},
    {"country_eng":"Chile","country_chn":"智利","country_code":"40228"},
    {"country_eng":"China","country_chn":"中国","country_code":"1"},
    {"country_eng":"Christmas Island","country_chn":"圣诞岛","country_code":"680000"},
    {"country_eng":"Cocos Islands","country_chn":"科科斯群岛","country_code":"540000"},
    {"country_eng":"Colombia","country_chn":"哥伦比亚","country_code":"40382"},
    {"country_eng":"Comoros","country_chn":"科摩罗","country_code":"70092"},
    {"country_eng":"Cook Islands","country_chn":"库克群岛","country_code":"610000"},
    {"country_eng":"Costa Rica","country_chn":"哥斯达黎加","country_code":"54019"},
    {"country_eng":"Croatia","country_chn":"克罗地亚","country_code":"47999"},
    {"country_eng":"CtedIvoire","country_chn":"科特迪瓦","country_code":"70074"},
    {"country_eng":"Cuba","country_chn":"古巴","country_code":"54039"},
    {"country_eng":"Curasao","country_chn":"库拉索","country_code":"54000"},
    {"country_eng":"Cyprus","country_chn":"塞浦路斯","country_code":"70032"},
    {"country_eng":"Cyprus UN Neutral Zone","country_chn":"塞浦路斯联合国中立区","country_code":"49596"},
    {"country_eng":"Czech Republic","country_chn":"捷克共和国","country_code":"46609"},
    {"country_eng":"Democratic Republic of the Congo","country_chn":"刚果民主共和国","country_code":"70081"},
    {"country_eng":"Denmark","country_chn":"丹麦","country_code":"51828"},
    {"country_eng":"Djibouti","country_chn":"吉布提","country_code":"70103"},
    {"country_eng":"Dominica","country_chn":"多米尼克","country_code":"54005"},
    {"country_eng":"Dominican Republic","country_chn":"多米尼加共和国","country_code":"54004"},
    {"country_eng":"East Timor","country_chn":"东帝汶","country_code":"70009"},
    {"country_eng":"Ecuador","country_chn":"厄瓜多尔","country_code":"39509"},
    {"country_eng":"Egypt","country_chn":"埃及","country_code":"70102"},
    {"country_eng":"El Salvador","country_chn":"萨尔瓦多","country_code":"54006"},
    {"country_eng":"United Kingdom","country_chn":"英国","country_code":"51441"},
    {"country_eng":"Equatorial Guinea","country_chn":"赤道几内亚","country_code":"70083"},
    {"country_eng":"Eritrea","country_chn":"厄立特里亚","country_code":"70104"},
    {"country_eng":"Estonia","country_chn":"爱沙尼亚","country_code":"47934"},
    {"country_eng":"Ethiopia","country_chn":"埃塞俄比亚","country_code":"70049"},
    {"country_eng":"Falkland Islands","country_chn":"福克兰群岛","country_code":"870000"},
    {"country_eng":"Faroe Islands","country_chn":"法罗群岛","country_code":"890000"},
    {"country_eng":"Fiji","country_chn":"斐济","country_code":"70008"},
    {"country_eng":"Finland","country_chn":"芬兰","country_code":"51372"},
    {"country_eng":"France","country_chn":"法国","country_code":"49841"},
    {"country_eng":"French Guiana","country_chn":"法属圭亚那","country_code":"40024"},
    {"country_eng":"French Polynesia","country_chn":"塔希提","country_code":"70007"},
    {"country_eng":"French Southern Territories","country_chn":"法属南部领地","country_code":"260000"},
    {"country_eng":"Gabon","country_chn":"加蓬","country_code":"70084"},
    {"country_eng":"Gambia","country_chn":"冈比亚","country_code":"70058"},
    {"country_eng":"Gaza Strip","country_chn":"加沙地带","country_code":"44504"},
    {"country_eng":"Georgia","country_chn":"格鲁吉亚","country_code":"70028"},
    {"country_eng":"Germany","country_chn":"德国","country_code":"50664"},
    {"country_eng":"Ghana","country_chn":"加纳","country_code":"70075"},
    {"country_eng":"Gibraltar","country_chn":"直布罗陀","country_code":"70003"},
    {"country_eng":"Greece","country_chn":"希腊","country_code":"46873"},
    {"country_eng":"Greenland","country_chn":"格陵兰（丹）","country_code":"51820"},
    {"country_eng":"Grenada","country_chn":"格林纳达","country_code":"54012"},
    {"country_eng":"Guadeloupe","country_chn":"瓜德罗普","country_code":"54017"},
    {"country_eng":"Guam","country_chn":"关岛","country_code":"1070000"},
    {"country_eng":"Guatemala","country_chn":"危地马拉","country_code":"54008"},
    {"country_eng":"Guernsey","country_chn":"根西岛","country_code":"940000"},
    {"country_eng":"Guinea","country_chn":"几内亚","country_code":"70061"},
    {"country_eng":"Guinea-Bissau","country_chn":"几内亚比绍","country_code":"70060"},
    {"country_eng":"Guyana","country_chn":"圭亚那","country_code":"40540"},
    {"country_eng":"Haiti","country_chn":"海地","country_code":"54029"},
    {"country_eng":"Heard Island and McDonald Islands","country_chn":"赫德岛和麦克唐纳群岛","country_code":"1090000"},
    {"country_eng":"Honduras","country_chn":"洪都拉斯","country_code":"54002"},
    {"country_eng":"Hungary","country_chn":"匈牙利","country_code":"46974"},
    {"country_eng":"Iceland","country_chn":"冰岛","country_code":"52448"},
    {"country_eng":"India","country_chn":"印度","country_code":"31080"},
    {"country_eng":"Indonesia","country_chn":"印度尼西亚","country_code":"31030"},
    {"country_eng":"Iran","country_chn":"伊朗","country_code":"70071"},
    {"country_eng":"Iraq","country_chn":"伊拉克","country_code":"70066"},
    {"country_eng":"Ireland","country_chn":"爱尔兰","country_code":"52012"},
    {"country_eng":"Isle of Man","country_chn":"马恩岛","country_code":"52233"},
    {"country_eng":"Israel","country_chn":"以色列","country_code":"70063"},
    {"country_eng":"Italy","country_chn":"意大利","country_code":"49987"},
    {"country_eng":"Jamaica","country_chn":"牙买加","country_code":"54013"},
    {"country_eng":"Japan","country_chn":"日本","country_code":"26000"},
    {"country_eng":"Jersey","country_chn":"泽西岛","country_code":"1250000"},
    {"country_eng":"Jordan","country_chn":"约旦","country_code":"70062"},
    {"country_eng":"Kazakhstan","country_chn":"哈萨克斯坦","country_code":"70023"},
    {"country_eng":"Kenya","country_chn":"肯尼亚","country_code":"70096"},
    {"country_eng":"Kiribati","country_chn":"基里巴斯","country_code":"1320000"},
    {"country_eng":"Kosovo","country_chn":"科索沃","country_code":"70030"},
    {"country_eng":"Kuwait","country_chn":"科威特","country_code":"70070"},
    {"country_eng":"Kyrgyzstan","country_chn":"吉尔吉斯斯坦","country_code":"70022"},
    {"country_eng":"Laos","country_chn":"老挝","country_code":"70012"},
    {"country_eng":"Latvia","country_chn":"拉脱维亚","country_code":"47765"},
    {"country_eng":"Lebanon","country_chn":"黎巴嫩","country_code":"70064"},
    {"country_eng":"Lesotho","country_chn":"莱索托","country_code":"70037"},
    {"country_eng":"Liberia","country_chn":"利比里亚","country_code":"70073"},
    {"country_eng":"Libya","country_chn":"利比亚","country_code":"70056"},
    {"country_eng":"Liechtenstein","country_chn":"列支敦士登","country_code":"70004"},
    {"country_eng":"Lithuania","country_chn":"立陶宛","country_code":"70017"},
    {"country_eng":"Luxembourg","country_chn":"卢森堡","country_code":"50353"},
    {"country_eng":"Macedonia","country_chn":"马其顿","country_code":"70029"},
    {"country_eng":"Madagascar","country_chn":"马达加斯加","country_code":"70091"},
    {"country_eng":"Malawi","country_chn":"马拉维","country_code":"70039"},
    {"country_eng":"Malaysia","country_chn":"马来西亚","country_code":"31190"},
    {"country_eng":"Maldives","country_chn":"马尔代夫","country_code":"31180"},
    {"country_eng":"Mali","country_chn":"马里","country_code":"70046"},
    {"country_eng":"Malta","country_chn":"马耳他","country_code":"70006"},
    {"country_eng":"Marshall Islands","country_chn":"马绍尔群岛","country_code":"1540000"},
    {"country_eng":"Martinique","country_chn":"马提尼克","country_code":"54007"},
    {"country_eng":"Mauritania","country_chn":"毛里塔尼亚","country_code":"70055"},
    {"country_eng":"Mauritius","country_chn":"毛里求斯","country_code":"65533"},
    {"country_eng":"Mayotte","country_chn":"马约特","country_code":"70093"},
    {"country_eng":"Mexico","country_chn":"墨西哥","country_code":"54025"},
    {"country_eng":"Micronesia","country_chn":"密克罗尼西亚","country_code":"900000"},
    {"country_eng":"Moldova","country_chn":"摩尔多瓦","country_code":"70019"},
    {"country_eng":"Monaco","country_chn":"摩纳哥","country_code":"51168"},
    {"country_eng":"Mongolia","country_chn":"蒙古","country_code":"70015"},
    {"country_eng":"Montenegro","country_chn":"黑山","country_code":"70020"},
    {"country_eng":"Montserrat","country_chn":"蒙特塞拉特","country_code":"1640000"},
    {"country_eng":"Morocco","country_chn":"摩洛哥","country_code":"70052"},
    {"country_eng":"Mozambique","country_chn":"莫桑比克","country_code":"70088"},
    {"country_eng":"Myanmar","country_chn":"缅甸","country_code":"70014"},
    {"country_eng":"Namibia","country_chn":"纳米比亚","country_code":"70086"},
    {"country_eng":"Nauru","country_chn":"瑙鲁","country_code":"1800000"},
    {"country_eng":"Nepal","country_chn":"尼泊尔","country_code":"31220"},
    {"country_eng":"Netherlands","country_chn":"荷兰","country_code":"52386"},
    {"country_eng":"New Caledonia","country_chn":"新喀里多尼亚","country_code":"1710000"},
    {"country_eng":"New Zealand","country_chn":"新西兰","country_code":"31230"},
    {"country_eng":"Nicaragua","country_chn":"尼加拉瓜","country_code":"54032"},
    {"country_eng":"Niger","country_chn":"尼日尔","country_code":"70045"},
    {"country_eng":"Nigeria","country_chn":"尼日利亚","country_code":"70078"},
    {"country_eng":"Niue","country_chn":"纽埃","country_code":"1760000"},
    {"country_eng":"Norfolk Island","country_chn":"诺福克岛","country_code":"1730000"},
    {"country_eng":"Northern Mariana Islands","country_chn":"北马里亚纳群岛","country_code":"1610000"},
    {"country_eng":"North Korea","country_chn":"朝鲜","country_code":"70010"},
    {"country_eng":"Norway","country_chn":"挪威","country_code":"52164"},
    {"country_eng":"Oman","country_chn":"阿曼","country_code":"70099"},
    {"country_eng":"Pakistan","country_chn":"巴基斯坦","country_code":"70035"},
    {"country_eng":"Palau","country_chn":"帕劳","country_code":"1880000"},
    {"country_eng":"Palestina","country_chn":"巴勒斯坦","country_code":"54030"},
    {"country_eng":"Panama","country_chn":"巴拿马","country_code":"54021"},
    {"country_eng":"Papua New Guinea","country_chn":"巴布亚新几内亚","country_code":"1890000"},
    {"country_eng":"Paraguay","country_chn":"巴拉圭","country_code":"40879"},
    {"country_eng":"Peru","country_chn":"秘鲁","country_code":"40465"},
    {"country_eng":"Philippines","country_chn":"菲律宾","country_code":"31260"},
    {"country_eng":"Pitcairn Islands","country_chn":"皮特凯恩群岛","country_code":"1850000"},
    {"country_eng":"Poland","country_chn":"波兰","country_code":"47200"},
    {"country_eng":"Portugal","country_chn":"葡萄牙","country_code":"51933"},
    {"country_eng":"Puerto Rico","country_chn":"波多黎各","country_code":"54028"},
    {"country_eng":"Qatar","country_chn":"卡塔尔","country_code":"70068"},
    {"country_eng":"Republic of the Congo","country_chn":"刚果共和国","country_code":"70085"},
    {"country_eng":"Reunion","country_chn":"留尼汪","country_code":"70089"},
    {"country_eng":"Romania","country_chn":"罗马尼亚","country_code":"48258"},
    {"country_eng":"Russia","country_chn":"俄罗斯","country_code":"70034"},
    {"country_eng":"Rwanda","country_chn":"卢旺达","country_code":"70043"},
    {"country_eng":"Saint Barthelemy","country_chn":"圣巴泰勒米","country_code":"40177"},
    {"country_eng":"Saint Kitts and Nevis","country_chn":"圣基茨和尼维斯","country_code":"54010"},
    {"country_eng":"Saint Lucia","country_chn":"圣卢西亚","country_code":"54035"},
    {"country_eng":"Saint Martin","country_chn":"法属圣马丁","country_code":"1470000"},
    {"country_eng":"Saint Pierre and Miquelon","country_chn":"圣皮埃尔和密克隆群岛","country_code":"54034"},
    {"country_eng":"Saint Vincent and the Grenadines","country_chn":"圣文森特和格林纳丁斯","country_code":"54014"},
    {"country_eng":"Samoa","country_chn":"萨摩亚","country_code":"2530000"},
    {"country_eng":"San Marino","country_chn":"圣马力诺","country_code":"70005"},
    {"country_eng":"Sao Tome and Principe","country_chn":"圣多美和普林西比","country_code":"70079"},
    {"country_eng":"Saudi Arabia","country_chn":"沙特阿拉伯","country_code":"70101"},
    {"country_eng":"Senegal","country_chn":"塞内加尔","country_code":"70059"},
    {"country_eng":"Serbia","country_chn":"塞尔维亚","country_code":"70031"},
    {"country_eng":"Seychelles","country_chn":"塞舌尔","country_code":"70094"},
    {"country_eng":"Sierra Leone","country_chn":"塞拉利昂","country_code":"70072"},
    {"country_eng":"Singapore","country_chn":"新加坡","country_code":"20000"},
    {"country_eng":"Sint Maarten","country_chn":"荷属圣马丁","country_code":"2700000"},
    {"country_eng":"Slovakia","country_chn":"斯洛伐克","country_code":"46751"},
    {"country_eng":"Slovenia","country_chn":"斯洛文尼亚","country_code":"70016"},
    {"country_eng":"Solomon Islands","country_chn":"所罗门群岛","country_code":"2090000"},
    {"country_eng":"Somalia","country_chn":"索马里","country_code":"70097"},
    {"country_eng":"South Africa","country_chn":"南非","country_code":"70087"},
    {"country_eng":"South Georgia and the South Sandwich Islands","country_chn":"南乔治亚和南桑威奇群岛","country_code":"2060000"},
    {"country_eng":"South Korea","country_chn":"韩国","country_code":"30000"},
    {"country_eng":"South Sudan","country_chn":"南苏丹","country_code":"70042"},
    {"country_eng":"Spain","country_chn":"西班牙","country_code":"51270"},
    {"country_eng":"Sri Lanka","country_chn":"斯里兰卡","country_code":"31130"},
    {"country_eng":"St Helena, Ascension, and T. Cunha","country_chn":"圣赫勒拿、阿森松和特里斯坦-达库尼亚","country_code":"42409"},
    {"country_eng":"Sudan","country_chn":"苏丹","country_code":"70105"},
    {"country_eng":"Suriname","country_chn":"苏里南","country_code":"39584"},
    {"country_eng":"Svalbard and Jan Mayen","country_chn":"斯瓦尔巴和扬马延","country_code":"2080000"},
    {"country_eng":"Swaziland","country_chn":"斯威士兰","country_code":"70038"},
    {"country_eng":"Sweden","country_chn":"瑞典","country_code":"51757"},
    {"country_eng":"Switzerland","country_chn":"瑞士","country_code":"50466"},
    {"country_eng":"Syria","country_chn":"叙利亚","country_code":"70065"},
    {"country_eng":"Tajikistan","country_chn":"塔吉克斯坦","country_code":"70025"},
    {"country_eng":"Tanzania","country_chn":"坦桑尼亚","country_code":"70095"},
    {"country_eng":"Thailand","country_chn":"泰国","country_code":"20500"},
    {"country_eng":"Togo","country_chn":"多哥","country_code":"70076"},
    {"country_eng":"Tokelau","country_chn":"托克劳","country_code":"2300000"},
    {"country_eng":"Tonga","country_chn":"汤加","country_code":"2330000"},
    {"country_eng":"Trinidad and Tobago","country_chn":"特立尼达和多巴哥","country_code":"54033"},
    {"country_eng":"Tunisia","country_chn":"突尼斯","country_code":"70106"},
    {"country_eng":"Turkey","country_chn":"土耳其","country_code":"48509"},
    {"country_eng":"Turkish Republic of Northern Cyprus","country_chn":"北塞浦路斯土耳其共和国","country_code":"52762"},
    {"country_eng":"Turkmenistan","country_chn":"土库曼斯坦","country_code":"70027"},
    {"country_eng":"Turks and Caicos Islands","country_chn":"特克斯和凯科斯群岛","country_code":"2250000"},
    {"country_eng":"Tuvalu","country_chn":"图瓦卢","country_code":"2370000"},
    {"country_eng":"Uganda","country_chn":"乌干达","country_code":"70041"},
    {"country_eng":"Ukraine","country_chn":"乌克兰","country_code":"49182"},
    {"country_eng":"United Arab Emirates","country_chn":"阿联酋","country_code":"70100"},
    {"country_eng":"United States","country_chn":"美国","country_code":"54003"},
    {"country_eng":"United States Minor Outlying Islands","country_chn":"美国本土外小岛屿","country_code":"54026"},
    {"country_eng":"Uruguay","country_chn":"乌拉圭","country_code":"39644"},
    {"country_eng":"Uzbekistan","country_chn":"乌兹别克斯坦","country_code":"70026"},
    {"country_eng":"Vanuatu","country_chn":"瓦努阿图","country_code":"2510000"},
    {"country_eng":"Vatican","country_chn":"梵蒂冈","country_code":"50415"},
    {"country_eng":"Venezuela","country_chn":"委内瑞拉","country_code":"39949"},
    {"country_eng":"Vietnam","country_chn":"越南","country_code":"32370"},
    {"country_eng":"Virgin Islands","country_chn":"美属维尔京群岛","country_code":"54031"},
    {"country_eng":"Wallis and Futuna","country_chn":"瓦利斯和富图纳","country_code":"2520000"},
    {"country_eng":"Western Sahara","country_chn":"西撒哈拉","country_code":"70054"},
    {"country_eng":"Yemen","country_chn":"也门","country_code":"70098"},
    {"country_eng":"Zambia","country_chn":"赞比亚","country_code":"70051"},
    {"country_eng":"Zimbabwe","country_chn":"津巴布韦","country_code":"70044"}
]`

var CountryCodeMap = make(map[int]CountryInfo)
var CountryBuild []CountryInfo = func() []CountryInfo {
	var countrys []CountrysConfig
	var countryInfos []CountryInfo
	json.Unmarshal([]byte(CountrysJson), &countrys)
	for _, country := range countrys {
		code, _ := strconv.Atoi(country.CountryCode)
		info := CountryInfo{
			Country:    country.CountryChn,
			CountryEng: country.CountryEng,
			Code:       code,
		}
		countryInfos = append(countryInfos, info)
		CountryCodeMap[code] = info
	}
	return countryInfos
}()

type CountryInfo struct {
	Country    string `json:"country"`
	CountryEng string `json:"country_eng"`
	Code       int    `json:"country_code"`
}

type CountrysConfig struct {
	CountryEng  string `json:"country_eng"`
	CountryChn  string `json:"country_chn"`
	CountryCode string `json:"country_code"`
}
